-- AQUASTROKE — Migration 002: Row Level Security
ALTER TABLE academies ENABLE ROW LEVEL SECURITY;
ALTER TABLE coaches ENABLE ROW LEVEL SECURITY;
ALTER TABLE seasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE athletes ENABLE ROW LEVEL SECURITY;
ALTER TABLE trial_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE adapt_prescriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE files ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION get_my_academy_id() RETURNS UUID AS $$ SELECT academy_id FROM coaches WHERE user_id=auth.uid() LIMIT 1; $$ LANGUAGE sql SECURITY DEFINER STABLE;
CREATE OR REPLACE FUNCTION get_my_role() RETURNS TEXT AS $$ SELECT role FROM coaches WHERE user_id=auth.uid() LIMIT 1; $$ LANGUAGE sql SECURITY DEFINER STABLE;
DROP POLICY IF EXISTS "coaches_read_own_academy" ON academies;
CREATE POLICY "coaches_read_own_academy" ON academies FOR SELECT USING (id=get_my_academy_id());
DROP POLICY IF EXISTS "coaches_read_same_academy" ON coaches;
CREATE POLICY "coaches_read_same_academy" ON coaches FOR SELECT USING (academy_id=get_my_academy_id());
DROP POLICY IF EXISTS "coaches_update_own_profile" ON coaches;
CREATE POLICY "coaches_update_own_profile" ON coaches FOR UPDATE USING (user_id=auth.uid());
DROP POLICY IF EXISTS "coaches_read_season" ON seasons;
CREATE POLICY "coaches_read_season" ON seasons FOR SELECT USING (academy_id=get_my_academy_id());
DROP POLICY IF EXISTS "head_coach_manage_season" ON seasons;
CREATE POLICY "head_coach_manage_season" ON seasons FOR ALL USING (academy_id=get_my_academy_id() AND get_my_role() IN ('ADMIN','HEAD_COACH'));
DROP POLICY IF EXISTS "coaches_read_academy_athletes" ON athletes;
CREATE POLICY "coaches_read_academy_athletes" ON athletes FOR SELECT USING (academy_id=get_my_academy_id());
DROP POLICY IF EXISTS "coaches_manage_athletes" ON athletes;
CREATE POLICY "coaches_manage_athletes" ON athletes FOR INSERT WITH CHECK (academy_id=get_my_academy_id() AND get_my_role() IN ('ADMIN','HEAD_COACH'));
DROP POLICY IF EXISTS "coaches_update_athletes" ON athletes;
CREATE POLICY "coaches_update_athletes" ON athletes FOR UPDATE USING (academy_id=get_my_academy_id());
DROP POLICY IF EXISTS "admin_delete_athletes" ON athletes;
CREATE POLICY "admin_delete_athletes" ON athletes FOR DELETE USING (academy_id=get_my_academy_id() AND get_my_role()='ADMIN');
DROP POLICY IF EXISTS "coaches_read_trials" ON trial_results;
CREATE POLICY "coaches_read_trials" ON trial_results FOR SELECT USING (academy_id=get_my_academy_id());
DROP POLICY IF EXISTS "coaches_insert_trials" ON trial_results;
CREATE POLICY "coaches_insert_trials" ON trial_results FOR INSERT WITH CHECK (academy_id=get_my_academy_id());
DROP POLICY IF EXISTS "coaches_update_trials" ON trial_results;
CREATE POLICY "coaches_update_trials" ON trial_results FOR UPDATE USING (academy_id=get_my_academy_id());
DROP POLICY IF EXISTS "head_coach_delete_trials" ON trial_results;
CREATE POLICY "head_coach_delete_trials" ON trial_results FOR DELETE USING (academy_id=get_my_academy_id() AND get_my_role() IN ('ADMIN','HEAD_COACH'));
DROP POLICY IF EXISTS "coaches_read_prescriptions" ON adapt_prescriptions;
CREATE POLICY "coaches_read_prescriptions" ON adapt_prescriptions FOR SELECT USING (academy_id=get_my_academy_id());
DROP POLICY IF EXISTS "coaches_insert_prescriptions" ON adapt_prescriptions;
CREATE POLICY "coaches_insert_prescriptions" ON adapt_prescriptions FOR ALL USING (academy_id=get_my_academy_id());
DROP POLICY IF EXISTS "coaches_read_files" ON files;
CREATE POLICY "coaches_read_files" ON files FOR SELECT USING (academy_id=get_my_academy_id());
DROP POLICY IF EXISTS "coaches_manage_files" ON files;
CREATE POLICY "coaches_manage_files" ON files FOR ALL USING (academy_id=get_my_academy_id());
DROP POLICY IF EXISTS "coaches_read_own_notifications" ON notifications;
CREATE POLICY "coaches_read_own_notifications" ON notifications FOR SELECT USING (academy_id=get_my_academy_id() AND (coach_id IS NULL OR coach_id=(SELECT id FROM coaches WHERE user_id=auth.uid() LIMIT 1)));
DROP POLICY IF EXISTS "coaches_update_notifications" ON notifications;
CREATE POLICY "coaches_update_notifications" ON notifications FOR UPDATE USING (coach_id=(SELECT id FROM coaches WHERE user_id=auth.uid() LIMIT 1));
DROP POLICY IF EXISTS "coaches_read_audit" ON audit_log;
CREATE POLICY "coaches_read_audit" ON audit_log FOR SELECT USING (academy_id=get_my_academy_id() AND get_my_role() IN ('ADMIN','HEAD_COACH'));
DROP POLICY IF EXISTS "system_insert_audit" ON audit_log;
CREATE POLICY "system_insert_audit" ON audit_log FOR INSERT WITH CHECK (true);
SELECT 'Migration 002 complete ✓' AS status;
